### ISSUE TITLE
Different APIs in minigraph_facts.py and minigraph.py in sonic-cfggen

### ISSUE THREAD

**Issue by stcheng** [Azure/sonic-mgmt#146] opened 2017-03-22 09:01 UTC
During code iterations, the two files become different in many cases.
It is hard to maintain two versions while there are a lot of jinja2 files rely on them.

**Comment by daall** [comment] 2020-04-28 21:07
Duplicate of #225.

**Closed by daall** 2020-04-28 21:07 UTC
Labels: Duplicate
