### ISSUE TITLE
DHCP relay test fails 

### ISSUE THREAD

**Issue by chitra-raghavan** [Azure/sonic-mgmt#976] opened 2019-06-25 10:54 UTC
**Description**

DHCP relay test fails . Upon sending DHCp discover packets from ptf , the  packets are getting flooded to the vlan ports rather than forwarding to server. 

Any changes in configuration needed wrt to   the feature? 

In the PR https://github.com/Azure/sonic-buildimage/pull/2832 , it is mentioned that the script has been  validated against the fixes. 

Topology: T0 

**Steps to reproduce the issue:**
1.    run dhcp_relay test

**Describe the results you received:**
from ptf , if  1000 DHCP  discover packets are sent ,all the packets  are  flooded to the vlan ports 

```
root@sonic-z9264f-9251:~# show int  counters  | grep U
      IFACE    STATE    RX_OK     RX_BPS    RX_UTIL    RX_ERR    RX_DRP    RX_OVR    TX_OK     TX_BPS    TX_UTIL    TX_ERR    TX_DRP    TX_OVR
  Ethernet4        U    1,001  98.79 B/s      0.00%         0         0         0        3   0.23 B/s      0.00%         0         0         0
  Ethernet8        U        0   0.00 B/s      0.00%         0         0         0    1,004  99.02 B/s      0.00%         0         0         0
 Ethernet12        U        0   0.00 B/s      0.00%         0         0         0    1,004  99.02 B/s      0.00%         0         0         0
 Ethernet16        U        0   0.00 B/s      0.00%         0         0         0    1,004  99.02 B/s      0.00%         0         0         0
 Ethernet20        U        0   0.00 B/s      0.00%         0         0         0    1,004  99.02 B/s      0.00%         0         0         0
 Ethernet24        U        0   0.00 B/s      0.00%         0         0         0    1,004  99.02 B/s      0.00%         0         0         0
 Ethernet28        U        0   0.00 B/s      0.00%         0         0         0    1,004  99.02 B/s      0.00%         0         0         0
 Ethernet32        U        0   0.00 B/s      0.00%         0         0         0    1,004  99.02 B/s      0.00%         0         0         0
 Ethernet36        U        0   0.00 B/s      0.00%         0         0         0    1,004  99.03 B/s      0.00%         0         0         0
 Ethernet40        U        0   0.00 B/s      0.00%         0         0         0    1,004  99.03 B/s      0.00%         0         0         0
 Ethernet44        U        0   0.00 B/s      0.00%         0         0         0    1,004  99.03 B/s      0.00%         0         0         0
 Ethernet48        U        0   0.00 B/s      0.00%         0         0         0    1,004  99.03 B/s      0.00%         0         0         0
 Ethernet52        U        0   0.00 B/s      0.00%         0         0         0    1,004  99.03 B/s      0.00%         0         0         0
 Ethernet56        U        0   0.00 B/s      0.00%         0         0         0    1,004  99.03 B/s      0.00%         0         0         0
 Ethernet60        U        0   0.00 B/s      0.00%         0         0         0    1,004  99.03 B/s      0.00%         0         0         0
 Ethernet64        U        0   0.00 B/s      0.00%         0         0         0    1,004  99.03 B/s      0.00%         0         0         0
 Ethernet68        U        0   0.00 B/s      0.00%         0         0         0    1,004  99.03 B/s      0.00%         0         0         0
 Ethernet72        U        0   0.00 B/s      0.00%         0         0         0    1,004  99.03 B/s      0.00%         0         0         0
 Ethernet76        U        0   0.00 B/s      0.00%         0         0         0    1,004  99.03 B/s      0.00%         0         0         0
 Ethernet80        U        0   0.00 B/s      0.00%         0         0         0    1,004  99.03 B/s      0.00%         0         0         0
 Ethernet84        U        0   0.00 B/s      0.00%         0         0         0    1,004  99.03 B/s      0.00%         0         0         0
 Ethernet88        U        0   0.00 B/s      0.00%         0         0         0    1,004  99.03 B/s      0.00%         0         0         0
 Ethernet92        U        0   0.00 B/s      0.00%         0         0         0    1,004  99.03 B/s      0.00%         0         0         0
 Ethernet96        U        0   0.00 B/s      0.00%         0         0         0    1,004  99.03 B/s      0.00%         0         0         0
Ethernet112        U      143   5.92 B/s      0.00%         0         0         0      191  11.38 B/s      0.00%         0         0         0
Ethernet116        U      123   4.47 B/s      0.00%         0         0         0      170  10.09 B/s      0.00%         0         0         0
Ethernet120        U      116   3.67 B/s      0.00%         0         0         0      116   3.73 B/s      0.00%         0         0         0
Ethernet124        U      128   5.20 B/s      0.00%         0         0         0      224  16.45 B/s      0.00%         0         0         0
root@sonic-z9264f-9251:~#

root@sonic-z9264f-9251:~# show vlan brief
+-----------+----------------+------------+----------------+-----------------------+
|   VLAN ID | IP Address     | Ports      | Port Tagging   | DHCP Helper Address   |
+===========+================+============+================+=======================+
|      1000 | 192.168.0.1/21 | Ethernet4  | untagged       | 192.0.0.1             |
|           |                | Ethernet8  | untagged       | 192.0.0.2             |
|           |                | Ethernet12 | untagged       | 192.0.0.3             |
|           |                | Ethernet16 | untagged       | 192.0.0.4             |
|           |                | Ethernet20 | untagged       |                       |
|           |                | Ethernet24 | untagged       |                       |
|           |                | Ethernet28 | untagged       |                       |
|           |                | Ethernet32 | untagged       |                       |
|           |                | Ethernet36 | untagged       |                       |
|           |                | Ethernet40 | untagged       |                       |
|           |                | Ethernet44 | untagged       |                       |
|           |                | Ethernet48 | untagged       |                       |
|           |                | Ethernet52 | untagged       |                       |
|           |                | Ethernet56 | untagged       |                       |
|           |                | Ethernet60 | untagged       |                       |
|           |                | Ethernet64 | untagged       |                       |
|           |                | Ethernet68 | untagged       |                       |
|           |                | Ethernet72 | untagged       |                       |
|           |                | Ethernet76 | untagged       |                       |
|           |                | Ethernet80 | untagged       |                       |
|           |                | Ethernet84 | untagged       |                       |
|           |                | Ethernet88 | untagged       |                       |
|           |                | Ethernet92 | untagged       |                       |
|           |                | Ethernet96 | untagged       |                       |
+-----------+----------------+------------+----------------+-----------------------+
root@sonic-z9264f-9251:~#
root@sonic-z9264f-9251:~# show ip route 192.0.0.1
Routing entry for 0.0.0.0/0
  Known via "bgp", distance 20, metric 0, best
  Last update 01:00:07 ago
  * 10.0.0.57, via PortChannel0001
  * 10.0.0.59, via PortChannel0002
  * 10.0.0.61, via PortChannel0003
  * 10.0.0.63, via PortChannel0004

root@sonic-z9264f-9251:~#

```

PTF log: 

```
root@2aed4d21c4b6:~# ptf --test-dir ptftests dhcp_relay_test.DHCPTest   --platform-dir ptftests  --platform remote  -t "hostname=\"sonic-z9264f-9251\";client_port_index=\"1\";client_iface_alias=\"Ethernet4\";leaf_port_indices=\"[31, 30, 29, 28]\";num_dhcp_servers=\"4\";server_ip=\"192.0.0.1\";relay_iface_ip=\"192.168.0.1\";relay_iface_mac=\"20:04:0f:36:94:49\";relay_iface_netmask=\"255.255.248.0\""  --relax 2>&1
WARNING: No route found for IPv6 destination :: (no default route?)
dhcp_relay_test.DHCPTest ... FAIL

======================================================================
FAIL: dhcp_relay_test.DHCPTest
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ptftests/dhcp_relay_test.py", line 523, in runTest
    self.verify_relayed_discover()
  File "ptftests/dhcp_relay_test.py", line 405, in verify_relayed_discover
    "Failed: Discover count of %d != %d" % (discover_count, num_expected_packets))
AssertionError: Failed: Discover count of 0 != 4

----------------------------------------------------------------------
Ran 1 test in 1.319s

FAILED (failures=1)
No handlers could be found for logger "dataplane"

******************************************
ATTENTION: SOME TESTS DID NOT PASS!!!

The following tests failed:
DHCPTest

******************************************
root@2aed4d21c4b6:~#
```

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

```
root@sonic-z9264f-9251:~# show ver

SONiC Software Version: SONiC.HEAD.16-dd0f005b
Distribution: Debian 9.9
Kernel: 4.9.0-9-2-amd64
Build commit: dd0f005b
Build date: Mon Jun 24 06:13:54 UTC 2019
Built by: johnar@jenkins-worker-4

Platform: x86_64-dellemc_z9264f_c3538-r0
HwSKU: DellEMC-Z9264f-Q64
ASIC: broadcom
Serial Number: CN030K8MDND0091M0007
Uptime: 18:55:32 up  1:00,  2 users,  load average: 0.80, 0.64, 0.66

Docker images:
REPOSITORY                 TAG                 IMAGE ID            SIZE
docker-syncd-brcm          HEAD.16-dd0f005b    19f8ba4b4940        392MB
docker-syncd-brcm          latest              19f8ba4b4940        392MB
docker-lldp-sv2            HEAD.16-dd0f005b    d40a9e9326c2        299MB
docker-lldp-sv2            latest              d40a9e9326c2        299MB
docker-dhcp-relay          HEAD.16-dd0f005b    15bb55012b69        288MB
docker-dhcp-relay          latest              15bb55012b69        288MB
docker-database            HEAD.16-dd0f005b    386c2ca27d09        280MB
docker-database            latest              386c2ca27d09        280MB
docker-snmp-sv2            HEAD.16-dd0f005b    c2806a211522        313MB
docker-snmp-sv2            latest              c2806a211522        313MB
docker-orchagent           HEAD.16-dd0f005b    5964e205d97e        319MB
docker-orchagent           latest              5964e205d97e        319MB
docker-teamd               HEAD.16-dd0f005b    67e085abd18e        301MB
docker-teamd               latest              67e085abd18e        301MB
docker-sonic-telemetry     HEAD.16-dd0f005b    1f57a5ed8e82        302MB
docker-sonic-telemetry     latest              1f57a5ed8e82        302MB
docker-router-advertiser   HEAD.16-dd0f005b    87994f130ac2        280MB
docker-router-advertiser   latest              87994f130ac2        280MB
docker-platform-monitor    HEAD.16-dd0f005b    23496540f484        326MB
docker-platform-monitor    latest              23496540f484        326MB
docker-fpm-frr             HEAD.16-dd0f005b    0650202b1ed7        319MB
docker-fpm-frr             latest              0650202b1ed7        319MB

root@sonic-z9264f-9251:~#
```

**Comment by jleveque** [comment] 2019-06-25 21:22
Are both your image and sonic-mgmt up-to-date? DHCP relay changes were made recently to sonic-buildimage and then to sonic-mgmt to reflect them:

- https://github.com/Azure/sonic-buildimage/commit/552684fc0818e59e2591585e9da8929da1180305
- https://github.com/Azure/sonic-mgmt/commit/d571f18c65076d2687361e4297092d69754ca16e

We are not seeing this issue. If you can reproduce this with up-to-date source, we will need more information with regards to your configuration to investigate.

**Comment by chitra-raghavan** [comment] 2019-06-27 05:59
Thanks. We are using latest master sonic-buildimage and synced all files in sonic-mgmt repo. We will re-check out environment and get  back.

**Comment by gord1306** [comment] 2019-06-27 07:37
Hi, I also have the same issue.  My environment is earlier than the commit-id that @jleveque mentioned.

My environment are:
 - Azure/sonic-buildimage@ [f0cfa85](https://github.com/Azure/sonic-buildimage/commit/f0cfa85059159e80b6ede1dc937d5208dd4b7728)
 - Azure/sonic-mgmt@ [475e3e15](https://github.com/Azure/sonic-mgmt/commit/475e3e1514ea433fc33f3703c03ba676c324b401)

Is this fail normally?? if my sonic-mgmt and image are both earlier than the latest dhcp_relay commit ?

**Comment by gord1306** [comment] 2019-06-29 16:26
Hi @chitra-raghavan 
Did you try to capture packet in PTF container and compare with the packet which is expected by dhcp_relay_test.py. In my side, I used tcpdump to capture packet in the PTF container, and the packet length seems length 4 bytes than the expected packet.

**Comment by jleveque** [comment] 2019-07-01 18:29
@gord1306: Thanks for the info. So the test is failing because the actual packet length does not match the expected length? Which packet is failing -- Discover, Offer, Request or Ack?

**Comment by gord1306** [comment] 2019-07-08 06:40
Hi @jleveque: for the byte length issue that my mentioned before, it should be my hardware issue. I use another broadcom switch, and I found the Circuit ID field does not match as dhcp_relay_test.py expected. The expected name is "EthernetX" but the switch's dhcp relay use alias name. Have you ever comapre this filed?

**Comment by jleveque** [comment] 2019-07-08 18:35
@gord1306: Thanks for the info. The expected behavior is for the DHCP relay to insert the port alias into the Circuit ID field, and the Ansible test should also set `client_iface_alias` to the port alias in dhcp_relay.yml, therefore this should not fail. How are you running the test?

**Comment by gord1306** [comment] 2019-07-09 01:24
@jleveque in current dhcp_relay.yml, it uses the fact "minigraph_vlans" to obtain the client ports alias, but when I checked how minigraph_vlans obtain this info via minigraph_facts.py, I found it uses the info of vlans which only contain port interfaces' name no port interfaces' alias.  The port interface's alias is only stored in "minigraph_ports".  

How I verify the test. I use the original dhcp_relay.yml to test, and it is failed and stop due to the discover fail in ptftest. Then I manually execute the ptftest again with changing the client_iface_alias to real port interfaces' alias, then all test cases of ptftest are pass. So I send #998  for this issue.

**Comment by jleveque** [comment] 2019-07-09 19:25
Resolved by https://github.com/Azure/sonic-mgmt/pull/998. (Thanks, @gord1306!).

@chitra-raghavan: Please try again with the latest code, and let us know if this is resolved for you, too.

**Comment by chitra-raghavan** [comment] 2019-07-12 08:32
@jleveque , with latest code changes , the script passed

**Comment by jleveque** [comment] 2019-07-12 17:41
Great to hear, @chitra-raghavan! Thanks again to @gord1306 for tracking down and fixing the issue. I will close this issue.

**Closed by jleveque** 2019-07-12 17:41 UTC
